### ISSUE TITLE
Move dmd repositories to dmdmtg organization

### ISSUE THREAD

**Issue by DrDaveD** [shattered/dmd-layers#1]
Hi Sergey,

I'm Dave Dykstra, the person who created a lot of the dmd software packages that you imported into github repositories several years back.  Thank you for that.  I am now trying to help somebody who is setting up a 730 terminal in a museum, and have ported the dmd-layers package to compile on a modern 64-bit Debian linux and so have a patch to apply.  I would like to gather all of the software together so I created a github organization called 'dmdmtg' and invited you to be a co-owner. Could you please transfer all your dmd-related repositories there?  If you then still want to keep a copy you could fork them, but I'd like that to be the base.

Thanks,

Dave

**Comment by shattered** [comment]
Hi -- sure, I've started transfers.

**Comment by DrDaveD** [comment]
Awesome, thank you.
